### ISSUE TITLE
server.js 코드 조정 부탁드립니다.

### ISSUE THREAD

**Issue by Buhwi** [rlaxodud6842/Tigers_crawler#3]
c708bd660ca1794e548eebf79f435b8c87fd6b5a 현재 server.js 코드 종료시 데이터가 남아있지 않고 삭제되는 문제가 있습니다. 확인후 수정 부탁드립니다.

**Comment by Kimdaeeon-DG** [comment]
MySQL로 데이터베이스를 구현하여 이제 코드 종료 이후에도 회원가입을 한 값이 남아있습니다.
