### ISSUE TITLE
현재 학기별 성적 조회 기능 추가 요청

### ISSUE THREAD

**Issue by Buhwi** [rlaxodud6842/Tigers_crawler#5]
현재 tts 변환이 전체 성적으로 이루어지고 있음. 각 학기별로 조회가 되도록 기능 추가 요청

**Comment by rlaxodud6842** [comment]
학기별 조회를 하려면, 학기를 먼저 입력을 받아야해서 조회 희망 학기를 먼저 받는걸 구현해야할것 같습니다. 또한, Gpt에게 전체성적을 줄 필요 없이, 희망 학기 성적만 주면 실행이 더 빨라질것으로 예상됩니다.

**Comment by rlaxodud6842** [comment]
Selective Grade 브랜치에 개념적으로 구현은 해보았습니다. 
4eca981
나중에 같이보고 구체화 합시다
