### ISSUE TITLE
Window기준 Node.js 서버 호스팅 IP 이슈

### ISSUE THREAD

**Issue by rlaxodud6842** [rlaxodud6842/Tigers_crawler#6]
포트를 `0.0.0.0` -> `127.0.0.1` 로 하니 정상 작동 되었습니다.

**Comment by Buhwi** [comment]
이런 문제가 있는줄은 맥으로만 해서 몰랐네요 감사합니다

**Comment by rlaxodud6842** [comment]
또한  `const pythonExecutable = path.join(__dirname, '../venv/Scripts/python.exe');` 를 추가해 파이썬 인터프리터를 설정해줘야 하네요
